name: user_repository
description: Dart package that manages user doamin
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  build_runner: ^2.0.0
  cloud_firestore: 
  equatable:
  firebase_auth: 
  json_annotation: ^4.0.0
  json_serializable: ^4.0.2
  meta: 